# Generated by Django 5.1.6 on 2025-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Totalbeds', models.IntegerField()),
                ('Availablebeds', models.IntegerField()),
                ('Returnname', models.CharField(max_length=100)),
            ],
        ),
    ]
